---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
    provisioner:
      require_chef_omnibus: 11.4.4
suites:
  - name: default
    run_list:
      - recipe[dbass::default]
    attributes:
